version: '3.8'

services:
  forge:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4-turbo-preview}
      - DEBUG=${DEBUG:-True}
    volumes:
      - ./frameworks:/app/frameworks
      - ./templates:/app/templates
    restart: unless-stopped